### PR TITLE
add WebVTT support

### LINKED ISSUE #2: WebVTT support
Continuing the discussion from [SwiftCommunityPodcast #15](https://github.com/SwiftCommunityPodcast/podcast/issues/15#issuecomment-460089441).

[Wikipedia: WebVTT](https://en.m.wikipedia.org/wiki/WebVTT)
[W3C: WebVTT Spec](https://w3c.github.io/webvtt/)

I think this is a great idea for moving forward. We'd need:

- Code for converting an `AmazonTranscribe.Transcript` value to a WebVTT-compatible string (should be quite easy).
- Code for parsing a WebVTT file into a general data structure. This would be great to have because it would allow us to edit the WebVTT transcript in WebVTT (which looks very editable with a text editor) and then read the edited file back in for possible conversion to other formats.
- The existing `AmazonTranscribe.Transcript` struct may be generalizable to act as a general data structure for storing a transcript, but I tend to think using a separate, more general data structure would be easier. For example, the distinction between punctuation characters and spoken words made by Amazon Transcribe isn't really important.

### PR DESCRIPTION
**Pull request by JulianKahnert**
fixes #2

### CODE REVIEW

**Comment by ole** [comment]
Good idea making the test file shorter. At least one test is quite slow with the full file.

**Comment by JulianKahnert** [comment]
Excatly. I wanted to speed up one test, from which I can start writing the parser.
I'd love to here what you think about (first iteration of) the WebVTT struct. Don't mince your words.

I will extend the CLI in the meantime.

btw: I found a way to get the WebVTT files from the Forschergeist Podcast. There are at least those two formats:
* https://forschergeist.de/podcast/fg060-klimawandel/?podlove_transcript=webvtt
* https://forschergeist.de/podcast/fg060-klimawandel/?podlove_transcript=json

**Comment by JulianKahnert** [comment]
Oh, I just saw your implementation von the makeMarkdown() ... I think I was a bit to quick on writing my own.

**Comment by ole** [comment]
Thanks so much for working on this @JulianKahnert. I checked out your code and ran it. The result looks great.

I do have some comments/suggestions on the code, but I'll need some time to write them down. I suggest we'll merge this as-is. We can always make changes later.

**Comment by ole** [comment]
@JulianKahnert I sent a PR with some changes (mostly cosmetics and documentation): #5. Nice work!

**Pull request merged**
